### ISSUE TITLE
log librato results

### ISSUE THREAD

**Issue by jmervine** [heroku/umpire#39]
@joshuatobin @reidmix Would it be worth logging the results from librato that umpire fetch? Like we're doing [in Laika](https://github.com/heroku/laika/blob/master/lib/mediators/alarm_message/logger.rb).

**Comment by reidmix** [comment]
might be worth it, if we included it in the response, we could also put it in watchtower result: https://github.com/heroku/watchtower-tng/blob/master/app/models/result.rb#L12-L23

**Comment by mikehale** [comment]
:+1: to including them in watchtower. It looks like they are already logged when in debug mode: https://github.com/heroku/umpire/blob/master/lib/umpire/librato_metrics.rb#L66-L68
