### ISSUE TITLE
composite metric queries should throw a 200 with missing metrics

### ISSUE THREAD

**Issue by joshuatobin** [heroku/umpire#46]
If you're trying to query a composite metric and one of the metric does not have a value it throws a 404, even with `empty_ok=true` . 

`at=internal_error class=TypeError message="can't convert String into Integer"`

**Comment by reidmix** [comment]
It should probably return a message like that when a single metric doesn't have data:  "no values for metric in range" -- or maybe the error that is returned from the composite metric request from librato.
