### ISSUE TITLE
Umpire Playbook needed.

### ISSUE THREAD

**Issue by jmervine** [heroku/umpire#54]
Umpire needs a playbook.

Here's some items that should go in there:

#### Links

- Repo -- https://github.com/heroku/umpire
- Space
  - Prod -- https://dashboard.heroku.com/orgs/heroku-sre/spaces/sre-va-prod/apps
  - Staging -- https://dashboard.heroku.com/orgs/heroku-sre/spaces/sre-va-staging/apps
- Pipeline -- https://dashboard.heroku.com/pipelines/a206f794-f589-4f28-93fc-7c2621f8e543
- Dashboard monitor -- https://dashboard.heroku.com/apps/umpire-api-va-prod/metrics/web?starting=2-hours-ago
- Watchtower monitor -- https://watchtower.herokai.com/apps/umpire

#### Splunking

```
# basic
index=main app="umpire-api-va-prod" 

# sans checks
index=main app="umpire-api-va-prod" action!="check"

# sans health && checks
index=main app="umpire-api-va-prod"  action!="health"
```

#### Logs

```
heroku logs -t -a umpire-api-va-prod
```

**Comment by jmervine** [comment]
@heroku/sre Anyone that has anything to add, or knows of specific topics that are missing, please add them.

**Comment by reidmix** [comment]
* Checking if librato is down (aka. when umpire's having problems with librato)
* Anything around investigating timeouts (like 404s that happened today)

**Comment by jmervine** [comment]
For investigating timeouts, we'll have to improve request logging in splunk.

**Comment by jmervine** [comment]
moved to gus
